### ISSUE TITLE
artifact is missing from Maven central

### ISSUE THREAD

**Issue by dlmutart** [ScalaConsultants/mesmer-akka-agent#170]
It appears that there is a problem publishing the akka core artifact to Maven repository.  Perhaps this is from recent repackaging from io.scalac to io.scalac.mesmer?   Haven't tried an SBT build yet, but with Maven:

     Could not find artifact io.scalac:mesmer-akka-core_2.13:jar:0.4 in central (https://repo.maven.apache.org/maven2)

When I look in Maven central, this artifact is indeed missing.

**Comment by lgajowy** [comment]
Version 0.4.1 works. Closing.
