### ISSUE TITLE
No metrics getting exported

### ISSUE THREAD

**Issue by saffyA** [ScalaConsultants/mesmer-akka-agent#250]
Hello!

I set up the example on my system and was able to see the Akka metrics generated by Mesmer and exported to Prometheus via the OTel collector. However when I try exactly the same set up with our Akka application, no metrics get exported. The logs seem to be very similar to the example application ( I can see the ByteBuddy & Mesmer extension log messages ). I also tried the logging exporter instead of the OTel exporter but again 0 metrics were logged. So it doesn't seem to be an exporting issue. Not sure if the metrics are getting generated and propogated the way they should. How can I debug this further?

**Comment by lgajowy** [comment]
Hi! 

Did you setup the metric reader in your app similar to what is done in the example? https://github.com/ScalaConsultants/mesmer-akka-agent/blob/0b9207fb27932b483c6dba694679a66a1c1a29c6/example/src/main/scala/example/Boot.scala#L45

**Comment by lgajowy** [comment]
Closing for now (lack of activity) but please feel free to reopen/ask further questions anyway if there are any.
