### ISSUE TITLE
The example confuses me

### ISSUE THREAD

**Issue by Roiocam** [ScalaConsultants/mesmer-akka-agent#329]
Your guys doing work is so great, there is no doubt about it

I'm trying to use this repo for my Akka Application Monitor, the exmaple was working well,but what confuses me is the otlp exporter in the example.

Why not just use the Prometheus exporter? It should be simple and easier to read the code, and the docker container environment could be simpler.

If needed, I can push a commit to "fix" the issue, just like my application does.

**Comment by Roiocam** [comment]
One possible reason for doing this is that Prometheus on the Docker container does not have direct access to localhost:port to collect application metrics, and the configuration of `prometheus.yml` may vary on different operating systems.

on other OS, the host is `host.docker.internal`
on MacOS, the host is `docker.for.mac.host.internal`

**Comment by worekleszczy** [comment]
Hello @Roiocam, thanks for opening an issue, I'm really glad you like the project so far 🙂 

The reason why we use this approach is that it is a recommended way of publishing metrics by OpenTelemetry. One of the advantages of using OpenTelemetry Collector is that it's vendor agnostic - if later on you decide that you want to publish metrics to some other backend / want to support more than one backend you can do it without any code changes. 

Additionally it has many more features - can read more [here](https://opentelemetry.io/docs/collector/).

Hope this helps and clear up some of the confusion 🙂

**Comment by Roiocam** [comment]
It's like protobuf for transferring between different programming languages, right?

I understand the versatility that comes with this approach, but for my APM using only Prometheus and Grafana, is the extra collector container overhead worth it?

**Comment by lgajowy** [comment]
> It's like protobuf for transferring between different programming languages, right?

Could be thought of it that way I guess. 

> I understand the versatility that comes with this approach, but for my APM using only Prometheus and Grafana, is the extra collector container overhead worth it?

> Why not just use the Prometheus exporter? It should be simple and easier to read the code, and the docker container environment could be simpler.

The general idea for mesmer as a project is to use opentelemetry-api only and not rely on exporters. This is why we set up the exporter in the example, not in the agent/extension etc. But that does not mean some other exporter could not be used. Like the [Prometheus](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/prometheus) one you mentioned. I personally haven't tried that one but it should work.

**Comment by Roiocam** [comment]
I have tried using Prometheus Exporter and they work fine.

Hard to disagree with the versatility that OTLP brings.

For now, I don't want to have extra collector overhead. So it's a trade-off .
